---
abstract: 'Read and write meta information'
author:
  - 'Phil Harvey (philharvey66 at gmail.com)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.143240, CPAN::Meta::Converter version 2.133380, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-ExifTool
no_index:
  directory:
    - t
    - inc
recommends:
  Archive::Zip: '0'
  Compress::Raw::Lzma: '0'
  Compress::Zlib: '0'
  Digest::MD5: '0'
  Digest::SHA: '0'
  IO::Compress::Brotli: '0'
  IO::Compress::RawDeflate: '0'
  IO::Uncompress::Brotli: '0'
  IO::Uncompress::RawInflate: '0'
  POSIX::strptime: '0'
  Time::HiRes: '0'
requires:
  perl: '5.004'
version: '13.39'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
